[build]
  command = "npm run build"  # Comando para build do seu projeto
  publish = "dist"           # Pasta onde está o conteúdo estático do seu site

[functions]
  directory = "netlify/functions"  # Diretório onde suas funções Netlify estão localizadas
